[versions]
kotlin = "2.1.10"
compose = "1.8.0-beta01"

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
